name: inter_knot
description: 绳网是一个游戏、技术交流平台
publish_to: none
version: 2.16.9+36
repository: https://github.com/share121/inter_knot

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  dart_jsonwebtoken: ^2.14.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_widget_from_html: ^0.15.2
  fwfh_svg: ^0.8.3
  fwfh_url_launcher: ^0.9.1
  get: ^4.6.6
  get_storage: ^2.1.1
  html: ^0.15.4
  intl: ^0.19.0
  logger: ^2.4.0
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^8.0.2
  pub_semver: ^2.1.4
  url_launcher: ^6.3.0
  waterfall_flow: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: icon.webp
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

msix_config:
  display_name: 绳网
  publisher_display_name: share121
  identity_name: com.share121.inter-knot
  msix_version: 1.0.0.0
  logo_path: icon.webp
  capabilities: internetClient
  languages: zh-CN, zh-TC, en-US
