name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PWD: ${{ secrets.PWD }}
  PEM: ${{ secrets.PEM }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.CLIENT_ID }}"
